#!/usr/bin/python3
import sys
import math

def isPerfectSquare(num):
    root = int(math.sqrt(num))

    if num == (root * root):
        return root
    return 0

def factor(string_num):
    num = int(string_num)
    count = -1
    root = 0

    if num % 2 == 0:
        print("{}={}*{}".format(num, num // 2, 2))
        return
    if num % 3 == 0:
        print("{}={}*{}".format(num, num // 3, 3))
        return
    if num % 5 == 0:
        print("{}={}*{}".format(num, num // 5, 5))
        return

    while root == 0:
        count += 1
        root = isPerfectSquare(num + (count ** 2))

    print("{}={}*{}".format(num, root + count, root - count))


if __name__ == "__main__":
    argv = sys.argv
    length = len(argv)

    if (length != 2):
        print("Usage {}".format(argv[0]))
        exit()

    filename = argv[1]

    with open(filename, 'r') as fs:
        lines = fs.readlines()

        for line in lines:
            factor(line.strip())
        fs.close()
