#!/usr/bin/python3
import sys
import math

def factor(string_num):
    num = int(string_num)
    root = int(math.sqrt(num))

    if num % 2 == 0:
        print("{}={}*{}".format(num, num // 2, 2))
        return
    if num % 3 == 0:
        print("{}={}*{}".format(num, num // 3, 3))
        return
    count = 5
    while count <= root:
        if num % count == 0:
            print("{}={}*{}".format(num, num // count, count))
            return
        if num % (count + 2) == 0:
            print("{}={}*{}".format(num, num // (count + 2), count + 2))
            return
        count += 6

    print("{}={}*{}".format(num, num, 1))


if __name__ == "__main__":
    argv = sys.argv
    length = len(argv)

    if (length != 2):
        print("Usage {}".format(argv[0]))
        exit()

    filename = argv[1]

    with open(filename, 'r') as fs:
        lines = fs.readlines()

        for line in lines:
            factor(line.strip())
        fs.close()
