#!/usr/bin/python3
import sys

def factor(string_num):
    num = int(string_num)
    root = int(pow(num, 0.5))

    if num % 2 == 0:
        print("{}={}*{}".format(num, num // 2, 2))
        return

    b = 3
    while b <= root:
        if num % b == 0:
              print("{}={}*{}".format(num, num // b, b))
              return
        b += 2

    print("{}={}*{}".format(num, num, 1))


if __name__ == "__main__":
    argv = sys.argv
    length = len(argv)

    if (length != 2):
        print("Usage {}".format(argv[0]))
        exit()

    filename = argv[1]

    with open(filename, 'r') as fs:
        lines = fs.readlines()

        for line in lines:
            factor(line.strip())
        fs.close()
